stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_eng.py
    deps:
    - src/features/feature_eng.py
    - data/processed
    params:
    - feature_engineering.test_size
    - feature_engineering.random_state
    - feature_engineering.max_df
    - feature_engineering.max_features
    - feature_engineering.min_df
    - feature_engineering.stop_words
    - feature_engineering.use_idf

    outs:
    - data/interim
    - models/tfidf.pkl

  model_training:
    cmd: python src/models/model_training.py
    deps:
    - data/interim
    - src/models/model_training.py
    params:
    - model_training.n_estimators
    - model_training.learning_rate
    - model_training.max_depth
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - ./data/interim
    - model.pkl
    - src/models/model_evaluation.py
    metrics:
    - metrics.json
    outs:
    - ./exp_inf.json

  model_registration:
    cmd: python src/models/model_registry.py
    deps:
    - ./exp_inf.json
    - src/models/model_registry.py

