data_ingestion:
  pages: 37     
  page_size: 100

feature_engineering:
  test_size: 0.2
  random_state: 42
  max_df: 0.9
  max_features: 200000
  min_df: 0.002
  stop_words: english
  use_idf: true

model_training:
  n_estimators: 180
  learning_rate: 0.1
  max_depth: 11

