feature_engineering:
  test_size: 0.2
  random_state: 42
  max_df: 0.85
  max_features: 1600
  min_df: 0.002
  stop_words: english
  use_idf: true

model_training:
  n_estimators: 150
  learning_rate: 0.1
  max_depth: 8

