data_ingestion_pages: 37
data_ingestion_page_size: 100
feature_engineering_test_size: 0.2
feature_engineering_random_state: 42
feature_engineering_max_df: 0.85
feature_engineering_max_features: 500
feature_engineering_min_df: 0.002
feature_engineering_stop_words: english
feature_engineering_use_idf: true
model_training_n_estimators: 150
model_training_learning_rate: 0.1
model_training_max_depth: 8
