name: CI

on: 
  push:
    branches:
      - master 

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download NLTK Resources
        run: |
          python -m nltk.downloader vader_lexicon
          python -m nltk.downloader stopwords
          python -m nltk.downloader wordnet
          python -m nltk.downloader punkt

      - name: Run pipeline
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}  # Using secrets for secure access
        run: |
          dvc repro
      - name: Run model tests 
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest ./tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python ./scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest ./tests/test_flask_app.py


